controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Corrección: Especificar cada importación con la clave resource

extra_routes_1:
    resource: routes2.yaml

extra_routes_2:
    resource: routes3.yaml




